### PR TITLE
Adding convenience radio-button-group component

### PR DESCRIPTION
**Pull request by ashrafhasson**
Hi there,

Thanks for the great addon. I've been using something very similar to this addon in my apps, only with the convenience wrapper for a group of options and thought it might be a useful addition.

Please let me know if this is something you'd be willing to merge into your addon :)

Thanks,

### CODE REVIEW

**Comment by raycohen** [comment]
Hi @ashrafhasson - we had started work on an ember radio group component earlier this year but didn't manage to push it to completion.

[Here's example usage](https://github.com/yapplabs/ember-radio-button/blob/5d57670db4ae20c35f18fb2c56358da5fd618a99/tests/dummy/app/templates/examples/basic.hbs#L20-L27)

And here's [the full diff](https://github.com/yapplabs/ember-radio-button/compare/ember-radio-group)

There's a difference in approach where the one we were working on. We wanted to make it flexible so that the user could still have a lot of control over the DOM that is produced. 

Without that flexibility I don't think a lot of users will benefit from this addition, and it isn't saving much work in the cases where it would help.

**Comment by ashrafhasson** [comment]
@raycohen thanks for the clarification, yeah noticed after the fact ..
The group doesn't take away the flexibility, it's just a convenience for cases where the options can be wrapped without having to specify them one by one. I suppose the sought flexibility you want is the ability to amend the DOM manually? But then, what's the function of the group?

Sorry to dwell on this, I would have loved to contribute :)

**Comment by raycohen** [comment]
Many of the issue we have opened on this project are folks needing more flexibility with the DOM, with what classnames and properties can be controlled from the component's API.

For example, someone might want to make a list of radio buttons, but they want to add 'my-extra-classname' to the 3rd radio button in their list, and they want to add an `image` element next to each radio in their list. Or they want to wrap three radios at a time in extra `div` elements.

There's no way to accomplish those kinds of requests with the component as written this way. That's what I mean when I'm saying this approach lacks flexibility. On top of that we're only saving people who do want this exact behavior from writing one 5-line `each` loop. From my view, it doesn't make sense for us from a project maintenance perspective.

If you still want to contribute, we can find other ways for you to do so.

**Comment by ashrafhasson** [comment]
Understood, Yes, it makes sense. Closing this PR for now.
Once more, thanks for the great addon! :)

**Comment by ashrafhasson** [comment]
so something like a JSON description of the options DOM is not probably of value either ..

**Pull request closed without merging**
