### PR TITLE
adds support for aria-describedby

### PR DESCRIPTION
**Pull request by cannjeff**
This adds support for setting the `aria-describedby` attribute on `radio-button-input` and having it set properly on the underlying `<input>`. Includes readme updates, a test, and an example.

### CODE REVIEW

**Comment by cannjeff** [comment]
@raycohen Whenever you get a chance, could you please take a look at this?

**Comment by raycohen** [comment]
looks good. if you pull in master, the issue with CI not passing should be resolved. I'll merge once green

**Comment by cannjeff** [comment]
@raycohen Oops, my bad. Should be good to go now. Thanks!

**Comment by raycohen** [comment]
published in version 1.2.2

**Pull request merged**
