### PR TITLE
Fixing `has-block` deprecation (incl. upgrade)

### PR DESCRIPTION
**Pull request by GabrielCousin**
Hey!

We've been running into the `has-block` deprecation (see https://github.com/yapplabs/ember-radio-button/issues/102)  recently and would love to address it!
I also re-did some Ember upgrade as well as refactoring component so the addon could be ready for Ember v4.
I can split the PR in several parts if you prefer but it seems unlikely to resolve the deprecation with upgrading Ember.

Let me know :)
Thanks!

### CODE REVIEW

**Comment by lukemelia** [comment]
I was probably premature in merging this. It drops test coverage for most of the Ember versions that this library supports.

**Comment by GabrielCousin** [comment]
Feel free to revert and reopen it if you prefer. My apologies for not being clear enough about the Ember upgrade. My feeling (and probably the one from other PR authors) is that it might be tricky to keep a large compatibility given the amount of required changes by Ember Octane and especially at the eve of v4

**Comment by nicksteffens** [comment]
With this introducing a breaking change in Ember < 3.10.0, Is there a reason not to cut a new major version?

**Comment by GabrielCousin** [comment]
That's right, it is implying to release a new major version for this

**Comment by gilest** [comment]
Would it be possible to cut a release with these changes? Could be an alpha or beta if we're uncertain that it's fully stable.

**Comment by GabrielCousin** [comment]
I tested the latest commit of master on our projects and the only notable change is that the value is not mutated anymore (which is I think introduced by Octane - arguments are immutable). It means you have to handle it by yourself within the change handler. I don't know if we can think of any alternative

**Comment by gilest** [comment]
> only notable change is that the value is not mutated anymore

Seems reasonable to me.

We'll want to mention this as a breaking change – could even add an **Upgrading to 3.0** section to the README

**Pull request merged**
