### PR TITLE
Polyfill `hasBlock` in the radio-button component

### PR DESCRIPTION
**Pull request by poteto**

### CODE REVIEW

**Comment by raycohen** [comment]
I tried this out against ember 1.13 and canary and it still gives me deprecation warnings.  Was there another aim you had in mind?

I have a refactor branch in the works using `hasBlock`.  The main task remaining there is to get it backwards compatible with ember versions before `hasBlock` was introduced.  (https://github.com/yapplabs/ember-radio-button/pull/20)

Happy to have extra feedback on that PR if you have a chance.

**Comment by poteto** [comment]
@raycohen Oh I'm sorry, I was using the github CLI to open the PR and my message must have been left out. This PR is meant to augment #20 so that it is backwards compatible with < `1.13`. Since `hasBlock` is not a thing in `1.12`, we can polyfill it for older Ember versions so that it still works.

**Comment by raycohen** [comment]
Ah, I see.  In #20 I'd removed the `wrapInLabelIfUsedAsBlock` function.  I think if I were to bring it back, users on newer embers would get deprecation warnings.  One option that was suggested to me was to use the Brocfile to give different versions of ember different code... wasn't sure how I felt about that.  Thoughts?

**Comment by raycohen** [comment]
It threw me off that you changed `wrapInLabelIfUsedAsBlock`.  What I want is this line, but only when ember <= 1.12
```
hasBlock: computed.bool('template').readOnly(),
```
Not sure how best to accomplish that

**Comment by poteto** [comment]
This PR should be merged prior to #20. 

You can then safely remove `wrapInLabelIfUsedAsBlock` and still have compatibility with older versions of Ember, as the `hasBlock` computed property polyfill also works in `1.13`. You can see that the [`hasBlock` helper](https://github.com/emberjs/ember.js/blob/e2355a6c7a4a1f64f50b8e00d8df326f9660c605/packages/ember-htmlbars/lib/compat/helper.js#L52) simply checks for the presence of a `template`, so the CP is equivalent. It's the same pattern I use in [`ember-cli-flash`](https://github.com/poteto/ember-cli-flash/blob/1.3.1/addon/components/flash-message.js#L108) and has worked very successfully.

**Comment by raycohen** [comment]
The implementation of `hasBlock` prevents that CP from being hit, so when I merge it into #20 I get no deprecation warnings like I was worried about.  Thanks!

**Pull request merged**
