### PR TITLE
Set the `for` attribute on the labeled-radio-button

### PR DESCRIPTION
**Pull request by poteto**
This PR is to allow the checking of a radio input by clicking on the
label that has its input id as its `for` attribute.

### CODE REVIEW

**Comment by poteto** [comment]
Apologies for the failed builds and rebases. I believe the issue is with Travis being on Phantom 1.9, and there being an existing bug with clicking on labels not triggering their `for` inputs – see https://github.com/ariya/phantomjs/issues/12032

**Comment by raycohen** [comment]
I was under the impression that we did not need to put the `for` attribute on the label because by wrapping the `input` in the `label` they are implicitly associated.  Does a unit test that triggers `click` on the label without these changes not work?

**Comment by poteto** [comment]
I updated Travis to use PhantomJS 2 – see https://github.com/travis-ci/travis-ci/issues/3225

@raycohen The change is primarily so we can pass the `id` to the `radio-button-input` from both the `labeled-radio-button` and `radio-button` component. In our use case, we have it so the `input` is not nested inside of the `label`, and this PR allows that to work

**Comment by raycohen** [comment]
Can we add an `id` to the nested `input` and still use the implicit association to bypass adding the `for`?  That should allow associating non-wrapping label elements.

**Comment by poteto** [comment]
I'm curious why you would prefer not to have it on the label, explicitly adding the `for` attribute is [recommended for accessibility](http://www.w3.org/TR/WCAG20-TECHS/H44.html#H44-examples), and we don't really lose anything by adding it

**Comment by raycohen** [comment]
This convinced me that the use of `for` is not always redundant:

`some assistive technologies do not correctly handle implicit labels`
http://www.w3.org/TR/2008/WD-WCAG20-TECHS-20080430/H44.html

Thanks!

**Pull request merged**
